---
groups:
- name: develop
  jobs:
  - build-accounts
  - itest-accounts
  - build-portfolio
  - itest-portfolio
  - build-quotes
  - build-web
- name: publish
  jobs:
  - accounts-major
  - accounts-minor
  - portfolio-major
  - portfolio-minor
  - quotes-major
  - quotes-minor
  - web-major
  - web-minor

jobs:
- name: build-accounts
  serial_groups: [ accounts-version ]
  plan:
  - get: pipeline
  - get: project
    resource: accounts-service
    trigger: true
  - get: version
    resource: accounts-version
    params: { pre: rc }
  - task: build
    file: pipeline/ci/build.yml
    params:
      ARTIFACT_ID: accounts
  - put: accounts-milestone
    params: { file: build/accounts-*.jar }
  - put: accounts-version
    params: { file: version/number }

- name: itest-accounts
  serial: true
  plan:
  - get: accounts-milestone
    passed: [ build-accounts ]
    trigger: true
  - get: accounts-service
    passed: [ build-accounts ]
  - task: itest
    file: accounts-service/ci/itest.yml
    params: &cf-params
      CF_API_URL: {{cf-api-url}}
      CF_USERNAME: {{cf-username}}
      CF_PASSWORD: {{cf-password}}
      CF_SKIP_SSL: {{cf-skip-ssl}}
      CF_ORG: {{cf-org}}
      CF_SPACE: {{cf-space}}
      CF_APP_NAME: {{cf-accounts-service-name}}
      CF_CONFIG_SERVER_URI: {{cf-config-server-uri}}
      CF_CONFIG_SERVER_LABEL: {{cf-config-server-label}}
      CF_DB_SERVICE: {{cf-db-service}}
      CF_APP_SERVICES: {{cf-accounts-service-services}}
      CF_ARTIFACT_ID: accounts

- name: accounts-major
  serial_groups: [ accounts-version ]
  plan:
  - get: accounts-version
    params: { bump: major, pre: rc }
  - put: accounts-version
    params: { file: accounts-version/number }

- name: accounts-minor
  public: true
  serial_groups: [ accounts-version ]
  plan:
  - get: accounts-version
    params: { bump: minor, pre: rc }
  - put: accounts-version
    params: { file: accounts-version/number }

- name: build-portfolio
  serial_groups: [ portfolio-version ]
  plan:
  - get: pipeline
  - get: project
    resource: portfolio-service
    trigger: true
  - get: version
    resource: portfolio-version
    params: { pre: rc }
  - task: build
    file: pipeline/ci/build.yml
    params:
      ARTIFACT_ID: portfolio
  - put: portfolio-milestone
    params: { file: build/portfolio-*.jar }
  - put: portfolio-version
    params: { file: version/number }

- name: itest-portfolio
  serial: true
  plan:
  - get: portfolio-milestone
    passed: [ build-portfolio ]
    trigger: true
  - get: portfolio-service
    passed: [ build-portfolio ]
  - task: itest
    file: portfolio-service/ci/itest.yml
    params:
      <<: *cf-params
      CF_APP_NAME: {{cf-portfolio-service-name}}
      CF_APP_SERVICES: {{cf-portfolio-service-services}}
      CF_ARTIFACT_ID: portfolio

- name: portfolio-major
  serial_groups: [ portfolio-version ]
  plan:
  - get: portfolio-version
    params: { bump: major, pre: rc }
  - put: portfolio-version
    params: { file: portfolio-version/number }

- name: portfolio-minor
  public: true
  serial_groups: [ portfolio-version ]
  plan:
  - get: portfolio-version
    params: { bump: minor, pre: rc }
  - put: portfolio-version
    params: { file: portfolio-version/number }

- name: build-quotes
  serial_groups: [ quotes-version ]
  plan:
  - get: pipeline
  - get: project
    resource: quotes-service
    trigger: true
  - get: version
    resource: quotes-version
    params: { pre: rc }
  - task: build
    file: pipeline/ci/build.yml
    params:
      ARTIFACT_ID: quotes
  - put: quotes-milestone
    params: { file: build/quotes-*.jar }
  - put: quotes-version
    params: { file: version/number }

- name: quotes-major
  serial_groups: [ quotes-version ]
  plan:
  - get: quotes-version
    params: { bump: major, pre: rc }
  - put: quotes-version
    params: { file: quotes-version/number }

- name: quotes-minor
  public: true
  serial_groups: [ quotes-version ]
  plan:
  - get: quotes-version
    params: { bump: minor, pre: rc }
  - put: quotes-version
    params: { file: quotes-version/number }

- name: build-web
  serial_groups: [ web-version ]
  plan:
  - get: pipeline
  - get: project
    resource: web-ui
    trigger: true
  - get: version
    resource: web-version
    params: { pre: rc }
  - task: build
    file: pipeline/ci/build.yml
    params:
      ARTIFACT_ID: web
  - put: web-milestone
    params: { file: build/web-*.jar }
  - put: web-version
    params: { file: version/number }

- name: web-major
  serial_groups: [ web-version ]
  plan:
  - get: web-version
    params: { bump: major, pre: rc }
  - put: web-version
    params: { file: web-version/number }

- name: web-minor
  public: true
  serial_groups: [ web-version ]
  plan:
  - get: web-version
    params: { bump: minor, pre: rc }
  - put: web-version
    params: { file: web-version/number }

resources:
- name: pipeline
  type: git
  source:
    uri: {{pipeline-git-uri}}
    branch: {{pipeline-git-branch}}
    privage_key: {{git-private-key}}

- name: accounts-service
  type: git
  source:
    uri: {{accounts-service-git-uri}}
    branch: {{accounts-service-git-branch}}
    private_key: {{git-private-key}}

- name: accounts-version
  type: semver
  source:
    driver: git
    uri: {{accounts-version-git-uri}}
    branch: {{accounts-version-git-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: accounts-milestone
  type: s3
  source:
    bucket: {{s3-bucket-milestone}}
    regexp: accounts-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: accounts-release
  type: s3
  source:
    bucket: {{s3-bucket-release}}
    regexp: accounts-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: portfolio-service
  type: git
  source:
    uri: {{portfolio-service-git-uri}}
    branch: {{portfolio-service-git-branch}}
    private_key: {{git-private-key}}

- name: portfolio-version
  type: semver
  source:
    driver: git
    uri: {{portfolio-version-git-uri}}
    branch: {{portfolio-version-git-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: portfolio-milestone
  type: s3
  source:
    bucket: {{s3-bucket-milestone}}
    regexp: portfolio-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: portfolio-release
  type: s3
  source:
    bucket: {{s3-bucket-release}}
    regexp: portfolio-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: quotes-service
  type: git
  source:
    uri: {{quotes-service-git-uri}}
    branch: {{quotes-service-git-branch}}
    private_key: {{git-private-key}}

- name: quotes-version
  type: semver
  source:
    driver: git
    uri: {{quotes-version-git-uri}}
    branch: {{quotes-version-git-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: quotes-milestone
  type: s3
  source:
    bucket: {{s3-bucket-milestone}}
    regexp: quotes-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: quotes-release
  type: s3
  source:
    bucket: {{s3-bucket-release}}
    regexp: quotes-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: web-ui
  type: git
  source:
    uri: {{web-ui-git-uri}}
    branch: {{web-ui-git-branch}}
    private_key: {{git-private-key}}

- name: web-version
  type: semver
  source:
    driver: git
    uri: {{web-version-git-uri}}
    branch: {{web-version-git-branch}}
    file: number
    initial_version: 1.0.0-rc.0
    private_key: {{git-private-key}}

- name: web-milestone
  type: s3
  source:
    bucket: {{s3-bucket-milestone}}
    regexp: web-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}

- name: web-release
  type: s3
  source:
    bucket: {{s3-bucket-release}}
    regexp: web-(.*).jar
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    endpoint: {{s3-endpoint}}
