---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: project
- name: version

outputs:
- name: build

params:
  TERM: dumb
  ARTIFACT_ID:

run:
  path: project/ci/build.sh
